*--------------------------------------------------------------------------------------------------------------------------------------------------------
* (ES) AUTOGENERADO - ¡¡ATENCIÓN!! - ¡¡NO PENSADO PARA EJECUTAR!! USAR SOLAMENTE PARA INTEGRAR CAMBIOS Y ALMACENAR CON HERRAMIENTAS SCM!!
* (EN) AUTOGENERATED - ATTENTION!! - NOT INTENDED FOR EXECUTION!! USE ONLY FOR MERGING CHANGES AND STORING WITH SCM TOOLS!!
*--------------------------------------------------------------------------------------------------------------------------------------------------------
*< FOXBIN2PRG: Version="1.19" SourceFile="fb2p_depto.dbf" /> (Solo para binarios VFP 9 / Only for VFP 9 binaries)
*

<TABLE>
	<MemoFile></MemoFile>
	<CodePage>1252</CodePage>
	<LastUpdate>2014/01/06</LastUpdate>
	<Database>fb2p_dbc.dbc</Database>
	<FileType>0x00000030</FileType>
	<FileType_Descrip>Visual FoxPro</FileType_Descrip>

	<FIELDS>
		<FIELD>
			<Name>DEPTO</Name>
			<Type>C</Type>
			<Width>10</Width>
			<Decimals>0</Decimals>
			<Null>.F.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp>depto_field_validation_rule()</Field_Valid_Exp>
			<Field_Valid_Text>depto_field_validation_message()</Field_Valid_Text>
			<Field_Default_Value>"Depto."</Field_Default_Value>
			<Table_Valid_Exp>fb2p_depto_record_rule_validation()</Table_Valid_Exp>
			<Table_Valid_Text>fb2p_depto_record_rule_validation_message()</Table_Valid_Text>
			<LongTableName>FB2P_DEPTO</LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp>__ri_delete_fb2p_depto()</Del_Trig_Exp>
			<TableComment>Comentario de "fb2p_depto"</TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
		<FIELD>
			<Name>DESCRIP</Name>
			<Type>C</Type>
			<Width>50</Width>
			<Decimals>0</Decimals>
			<Null>.F.</Null>
			<NoCPTran>.F.</NoCPTran>
			<Field_Valid_Exp></Field_Valid_Exp>
			<Field_Valid_Text></Field_Valid_Text>
			<Field_Default_Value></Field_Default_Value>
			<Table_Valid_Exp></Table_Valid_Exp>
			<Table_Valid_Text></Table_Valid_Text>
			<LongTableName></LongTableName>
			<Ins_Trig_Exp></Ins_Trig_Exp>
			<Upd_Trig_Exp></Upd_Trig_Exp>
			<Del_Trig_Exp></Del_Trig_Exp>
			<TableComment></TableComment>
			<Autoinc_Nextval>0</Autoinc_Nextval>
			<Autoinc_Step>0</Autoinc_Step>
		</FIELD>
	</FIELDS>


	<indexFile>FB2P_DEPTO.CDX</indexFile>

	<INDEXES>
		<INDEX>
			<TagName>DEPTO</TagName>
			<TagType>PRIMARY</TagType>
			<Key>DEPTO</Key>
			<Filter>depto=>"0"</Filter>
			<Order>ASCENDING</Order>
			<Collate>MACHINE</Collate>
		</INDEX>
	</INDEXES>

</TABLE>
