LPARAMETERS;
tcDirectory

DO CASE
 CASE VARTYPE(tcDirectory)#'C'
 CASE !INLIST(UPPER(tcDirectory),'?','/?','-?','/Help','-Help')
 OTHERWISE
  tcDirectory = JUSTFNAME(SYS(16))
  InfoScreen(tcDirectory)
  RETURN
ENDCASE

ADDPROPERTY(_SCREEN,'gvX1',tcDirectory)

CLEAR ALL

LOCAL;
 lcDir,;
 lcExt,;
 lcErr,;
 lcOldPath,;
 lcDirectory,;
 llNewGUID

LOCAL ARRAY;
 laActual(1)

lcDirectory = _SCREEN.gvX1
REMOVEPROPERTY(_SCREEN,'gvX1')

lcOldPath = FULLPATH(CURDIR())

DO CASE
 CASE EMPTY(lcDirectory)
  lcDir = ''
 CASE !DIRECTORY(lcDirectory) AND !FILE(lcDirectory)
  lcDir = ''
 CASE DIRECTORY(lcDirectory)
  lcDir = ADDBS(lcDirectory)
 OTHERWISE
  MESSAGEBOX('Nicht unterstützter Dateityp.')
  RETURN
ENDCASE

IF EMPTY(lcDir) THEN
 CLEAR
 lcDir = GETDIR('','','',64)
 IF ALLTRIM(lcDir)=='' THEN
  RETURN
 ENDIF &&ALLTRIM(lcDir)==''
ENDIF &&EMPTY(lcDir)

PUBLIC;
 poRegExp

*!*	poRegExp = CREATEOBJECT('VBScript.RegExp')
*!*	WITH poRegExp
*!*	 .IgnoreCase = .T.
*!*	 .GLOBAL     = .T.
*!*	 .MultiLine  = .T.
*!*	ENDWITH &&poRegExp

lcErr = ''
lcResult = ''
Get_CompareFiles(@laActual)
ScanDir(lcDir,@lcErr,lcDir,@laActual)
CD
IF !EMPTY(lcErr) THEN
 MESSAGEBOX('Fehler in der Zwischenablage gespeichert',0+48)
 _CLIPTEXT = SUBSTR(lcErr,3)
ENDIF &&!EMPTY(lcErr)
poRegExp = .NULL.
RELEASE;
 poRegExp

CD (lcOldPath)

PROCEDURE InfoScreen
 LPARAMETERS;
  tcProgram

 LOCAL;
  lcTemp     AS CHARACTER,;
  lnOldMemoW AS INTEGER

 TEXT TO lcTEMP NOSHOW textmerge
<<tcProgram>>
Removes files from old installation out og Thor installation directroy for FoxBin2Prg
Compares with a list of files, change proc Get_CompareFiles to add or remove files.
Run Read_InstallFiles.prg against INSTALLEDFILES directory to get the list of files.
Usage:
<<tcProgram>> [/?] [cDirectory]
 /?         Displays this text
 cDirectory optional directory to start from, subdirectories will be included
 ENDTEXT
 lnOldMemoW = SET("Memowidth")
 SET MEMOWIDTH TO 100
 ?lcTemp FONT 'Courier',6
 SET MEMOWIDTH TO lnOldMemoW
ENDPROC &&InfoScreen

PROCEDURE ScanDir
 LPARAMETERS;
  tcDir,;
  tcErr,;
  tcDir2,;
  taActual

 LOCAL;
  lnLoop1,;
  lcOldDir

 LOCAL ARRAY;
  laDir(1)

* SET STEP ON
 lcOldDir = FULLPATH(CURDIR())
 CD (tcDir)
 FOR lnLoop1 = 1 TO ADIR(laDir,'','D')
  IF INLIST(laDir(lnLoop1,1),'.','..') THEN
   LOOP
  ENDIF &&INLIST(laDir(lnLoop1,1),'.','..')
  ScanDir(ADDBS(tcDir+laDir(lnLoop1,1)),@tcErr,tcDir2,@taActual)
 ENDFOR &&lnLoop1
 Dir_Action(tcDir,@tcErr,tcDir2,@taActual)
 CD (lcOldDir)
ENDPROC &&ScanDir

PROCEDURE Dir_Action
 LPARAMETERS;
  tcDir,;
  tcErr,;
  tcDir2,;
  taActual

 LOCAL;
  lnStart AS INTEGER

 EXTERNAL ARRAY;
  taActual

 LOCAL ARRAY;
  laDir(1)

 tcDir2 = STRTRAN(tcDir,tcDir2,'')

 FOR lnStart = 1 TO ADIR(laDir,'*.*')
  IF EMPTY(ASCAN(taActual,tcDir2+laDir(lnStart,1))) THEN
   DELETE FILE JUSTFNAME(laDir(lnStart,1))
  ENDIF &&EMPTY(ASCAN(taActual,tcDir2+laDir(lnStart,1)))

 ENDFOR &&lnStart

 DIMENSION ;
  laDir(1)

 laDir = .F.
 ADIR(laDir,'*.*')
 IF EMPTY(laDir(1,1)) THEN
  CD ..
  TRY
    RMDIR JUSTFNAME(JUSTPATH(m.tcDir))
   CATCH
*incase there is a folder, the cheap ignore
    ?m.tcDir
  ENDTRY
 ENDIF &&EMPTY(laDir(1,1))

 RETURN
ENDPROC &&Dir_Action

PROCEDURE Get_CompareFiles
 LPARAMETERS;
  taActual

 EXTERNAL ARRAY;
  taActual

 LOCAL;
  lcTemp AS STRING

 TEXT TO lctemp NOSHOW
CONFIG\CONFIG.FPW
WINMERGEPORTABLE\APP\APPINFO\LAUNCHER\SPLASH.JPG
WINMERGEPORTABLE\APP\APPINFO\LAUNCHER\WINMERGEPORTABLE.INI
WINMERGEPORTABLE\APP\APPINFO\APPICON.ICO
WINMERGEPORTABLE\APP\APPINFO\APPICON_128.PNG
WINMERGEPORTABLE\APP\APPINFO\APPICON_16.PNG
WINMERGEPORTABLE\APP\APPINFO\APPICON_32.PNG
WINMERGEPORTABLE\APP\APPINFO\APPINFO.INI
WINMERGEPORTABLE\APP\APPINFO\INSTALLER.INI
WINMERGEPORTABLE\APP\DEFAULTDATA\SETTINGS\WINMERGE.REG
WINMERGEPORTABLE\APP\WINMERGE\DOCS\CHANGELOG.TXT
WINMERGEPORTABLE\APP\WINMERGE\DOCS\README-BASQUE.TXT
WINMERGEPORTABLE\APP\WINMERGE\DOCS\README-BRAZILIAN.TXT
WINMERGEPORTABLE\APP\WINMERGE\DOCS\README-BULGARIAN.TXT
WINMERGEPORTABLE\APP\WINMERGE\DOCS\README-CATALAN.TXT
WINMERGEPORTABLE\APP\WINMERGE\DOCS\README-CHINESESIMPLIFIED.TXT
WINMERGEPORTABLE\APP\WINMERGE\DOCS\README-CHINESETRADITIONAL.TXT
WINMERGEPORTABLE\APP\WINMERGE\DOCS\README-CROATIAN.TXT
WINMERGEPORTABLE\APP\WINMERGE\DOCS\README-DUTCH.TXT
WINMERGEPORTABLE\APP\WINMERGE\DOCS\README-FRENCH.TXT
WINMERGEPORTABLE\APP\WINMERGE\DOCS\README-GALICIAN.TXT
WINMERGEPORTABLE\APP\WINMERGE\DOCS\README-GREEK.TXT
WINMERGEPORTABLE\APP\WINMERGE\DOCS\README-JAPANESE.TXT
WINMERGEPORTABLE\APP\WINMERGE\DOCS\README-ROMANIAN.TXT
WINMERGEPORTABLE\APP\WINMERGE\DOCS\README-SERBIAN.TXT
WINMERGEPORTABLE\APP\WINMERGE\DOCS\README-SPANISH.TXT
WINMERGEPORTABLE\APP\WINMERGE\DOCS\README-SWEDISH.TXT
WINMERGEPORTABLE\APP\WINMERGE\DOCS\README-TURKISH.TXT
WINMERGEPORTABLE\APP\WINMERGE\DOCS\README-UKRAINIAN.TXT
WINMERGEPORTABLE\APP\WINMERGE\DOCS\README.TXT
WINMERGEPORTABLE\APP\WINMERGE\DOCS\RELEASENOTES.HTML
WINMERGEPORTABLE\APP\WINMERGE\DOCS\WINMERGE.CHM
WINMERGEPORTABLE\APP\WINMERGE\FILTERS\ADAMULTI.FLT
WINMERGEPORTABLE\APP\WINMERGE\FILTERS\ASPNET.FLT
WINMERGEPORTABLE\APP\WINMERGE\FILTERS\CSHARP_LOOSE.FLT
WINMERGEPORTABLE\APP\WINMERGE\FILTERS\DELPHI.FLT
WINMERGEPORTABLE\APP\WINMERGE\FILTERS\FILEFILTER.TMPL
WINMERGEPORTABLE\APP\WINMERGE\FILTERS\FRONTPAGE.FLT
WINMERGEPORTABLE\APP\WINMERGE\FILTERS\MASM.FLT
WINMERGEPORTABLE\APP\WINMERGE\FILTERS\MERGE_GNUC_LOOSE.FLT
WINMERGEPORTABLE\APP\WINMERGE\FILTERS\MERGE_VB_LOOSE.FLT
WINMERGEPORTABLE\APP\WINMERGE\FILTERS\MERGE_VC_LOOSE.FLT
WINMERGEPORTABLE\APP\WINMERGE\FILTERS\MICROSOFT_VISUAL_FOXPRO_FOXBIN2PRG.FLT
WINMERGEPORTABLE\APP\WINMERGE\FILTERS\SOURCECONTROL.FLT
WINMERGEPORTABLE\APP\WINMERGE\FILTERS\SYMBIAN.FLT
WINMERGEPORTABLE\APP\WINMERGE\FILTERS\XML_HTML.FLT
WINMERGEPORTABLE\APP\WINMERGE\LANG\AF.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\AR.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\AST.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\AZ.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\BA.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\BE.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\BG.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\BN.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\BR.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\CA.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\CS.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\CY.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\DA.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\DE.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\EL.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\EN.TTT
WINMERGEPORTABLE\APP\WINMERGE\LANG\EO.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\ES.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\ET.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\EU.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\EXT.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\FA.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\FI.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\FR.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\FUR.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\FY.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\GL.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\GU.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\HE.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\HI.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\HR.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\HU.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\HY.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\ID.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\IO.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\IS.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\IT.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\JA.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\KA.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\KK.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\KO.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\KU-CKB.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\KU.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\LT.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\LV.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\MK.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\MN.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\MR.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\MS.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\NB.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\NE.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\NL.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\NN.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\PA-IN.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\PL.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\PS.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\PT-BR.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\PT.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\RO.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\RU.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\SA.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\SI.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\SK.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\SL.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\SQ.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\SR-SPC.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\SR-SPL.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\SV.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\TA.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\TH.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\TR.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\TT.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\UG.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\UK.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\UZ.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\VA.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\VI.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\ZH-CN.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANG\ZH-TW.TXT
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\BASQUE.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\BRAZILIAN.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\BULGARIAN.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\CATALAN.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\CHINESESIMPLIFIED.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\CHINESETRADITIONAL.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\CROATIAN.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\CZECH.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\DANISH.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\DUTCH.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\FRENCH.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\GALICIAN.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\GERMAN.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\GREEK.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\HUNGARIAN.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\ITALIAN.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\JAPANESE.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\KOREAN.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\NORWEGIAN.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\PERSIAN.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\POLISH.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\PORTUGUESE.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\ROMANIAN.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\RUSSIAN.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\SERBIAN.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\SLOVAK.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\SLOVENIAN.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\SPANISH.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\SWEDISH.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\TURKISH.PO
WINMERGEPORTABLE\APP\WINMERGE\LANGUAGES\UKRAINIAN.PO
WINMERGEPORTABLE\APP\WINMERGE\MERGEPLUGINS\COMPAREMSEXCELFILES.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGEPLUGINS\COMPAREMSWORDFILES.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGEPLUGINS\DISPLAYXMLFILES.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGEPLUGINS\EDITOR ADDIN.SCT
WINMERGEPORTABLE\APP\WINMERGE\MERGEPLUGINS\IGNORECOLUMNS.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGEPLUGINS\IGNORECOMMENTSC.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGEPLUGINS\IGNOREFIELDSCOMMA.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGEPLUGINS\IGNOREFIELDSTAB.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGEPLUGINS\IGNORELEADINGLINENUMBERS.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGEPLUGINS\INSERT DATETIME.SCT
WINMERGEPORTABLE\APP\WINMERGE\MERGEPLUGINS\WATCHBEGINNINGOFLOG.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGEPLUGINS\WATCHENDOFLOG.DLL
WINMERGEPORTABLE\APP\WINMERGE\7Z.DLL
WINMERGEPORTABLE\APP\WINMERGE\7ZIP_PAD.XML
WINMERGEPORTABLE\APP\WINMERGE\CONTRIBUTORS.TXT
WINMERGEPORTABLE\APP\WINMERGE\FILES.TXT
WINMERGEPORTABLE\APP\WINMERGE\IGNORESECTIONMARKERS.INI
WINMERGEPORTABLE\APP\WINMERGE\LIBEXPAT.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGE7Z910U.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGE7Z911.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGE7Z911U.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGE7Z912.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGE7Z912U.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGE7Z913.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGE7Z913U.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGE7Z914.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGE7Z914U.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGE7Z915.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGE7Z915U.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGE7Z916.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGE7Z916U.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGE7Z917.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGE7Z917U.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGE7Z918.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGE7Z918U.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGE7Z919.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGE7Z919U.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGE7Z920.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGE7Z920U.DLL
WINMERGEPORTABLE\APP\WINMERGE\MERGELANG.DLL
WINMERGEPORTABLE\APP\WINMERGE\MFC90.DLL
WINMERGEPORTABLE\APP\WINMERGE\MFC90U.DLL
WINMERGEPORTABLE\APP\WINMERGE\MFCM90.DLL
WINMERGEPORTABLE\APP\WINMERGE\MFCM90U.DLL
WINMERGEPORTABLE\APP\WINMERGE\MICROSOFT.VC90.CRT.MANIFEST
WINMERGEPORTABLE\APP\WINMERGE\MICROSOFT.VC90.MFC.MANIFEST
WINMERGEPORTABLE\APP\WINMERGE\MSVCM90.DLL
WINMERGEPORTABLE\APP\WINMERGE\MSVCP90.DLL
WINMERGEPORTABLE\APP\WINMERGE\MSVCR90.DLL
WINMERGEPORTABLE\APP\WINMERGE\PCRE.DLL
WINMERGEPORTABLE\APP\WINMERGE\WINMERGEU.EXE
WINMERGEPORTABLE\DATA\SETTINGS\WINMERGE.REG
WINMERGEPORTABLE\DATA\SETTINGS\WINMERGEPORTABLESETTINGS.INI
WINMERGEPORTABLE\OTHER\HELP\IMAGES\DONATION_BUTTON.PNG
WINMERGEPORTABLE\OTHER\HELP\IMAGES\FAVICON.ICO
WINMERGEPORTABLE\OTHER\HELP\IMAGES\HELP_BACKGROUND_FOOTER.PNG
WINMERGEPORTABLE\OTHER\HELP\IMAGES\HELP_BACKGROUND_HEADER.PNG
WINMERGEPORTABLE\OTHER\HELP\IMAGES\HELP_LOGO_TOP.PNG
WINMERGEPORTABLE\OTHER\SOURCE\APPNAMEPORTABLE.INI
WINMERGEPORTABLE\OTHER\SOURCE\LAUNCHERLICENSE.TXT
WINMERGEPORTABLE\OTHER\SOURCE\PORTABLEAPPS.COMINSTALLERCUSTOM.NSH
WINMERGEPORTABLE\OTHER\SOURCE\README.TXT
WINMERGEPORTABLE\HELP.HTML
WINMERGEPORTABLE\WINMERGEPORTABLE.EXE
.GITIGNORE
CONVERT_VFP9_BIN_2_PRG.VBS
CONVERT_VFP9_PRG_2_BIN.VBS
FB2P_DIFF.EXE
FILENAME_CAPS.CFG
FILENAME_CAPS.EXE
FOXBIN2PRG.CFG.TXT
FOXBIN2PRG.DBF.CFG.TXT
FOXBIN2PRG.EXE
FOXBIN2PRG.ICO
FOXBIN2PRG.JPG
FOXBIN2PRG.PRG
FOXBIN2PRGVERSIONFILE.TXT
FOXBIN2PRG_KEYWORDS.CDX
FOXBIN2PRG_KEYWORDS.DBF
LICENSE
NORMALIZE_FILENAMES.VBS
PROPS_ALL.TXT
PROPS_CHECKBOX.TXT
PROPS_COLLECTION.TXT
PROPS_COMBOBOX.TXT
PROPS_COMMANDBUTTON.TXT
PROPS_COMMANDGROUP.TXT
PROPS_CONTAINER.TXT
PROPS_CONTROL.TXT
PROPS_CURSOR.TXT
PROPS_CURSORADAPTER.TXT
PROPS_DATAENVIRONMENT.TXT
PROPS_EDITBOX.TXT
PROPS_FORM.TXT
PROPS_FORMSET.TXT
PROPS_GRID.TXT
PROPS_GRID_COLUMN.TXT
PROPS_GRID_HEADER.TXT
PROPS_HYPERLINK.TXT
PROPS_IMAGE.TXT
PROPS_LABEL.TXT
PROPS_LINE.TXT
PROPS_LISTBOX.TXT
PROPS_OLEBOUND.TXT
PROPS_OPTIONGROUP.TXT
PROPS_OPTIONGROUP_OPTION.TXT
PROPS_PAGEFRAME.TXT
PROPS_PAGEFRAME_PAGE.TXT
PROPS_PRE_V1_19_22.TXT
PROPS_PROJECTHOOK.TXT
PROPS_RELATION.TXT
PROPS_REPORTLISTENER.TXT
PROPS_SEPARATOR.TXT
PROPS_SHAPE.TXT
PROPS_SPINNER.TXT
PROPS_TEXTBOX.TXT
PROPS_TIMER.TXT
PROPS_TOOLBAR.TXT
PROPS_XMLADAPTER.TXT
PROPS_XMLFIELD.TXT
PROPS_XMLTABLE.TXT
README.MD
VFP9_FOXBIN2PRG.VBS
FOXBIN2PRG.CFG
CLEAN_THORFOLDER.PRG
CLEAN_THORFOLDER.FXP
 ENDTEXT &&lcTemp

 ALINES(taActual,lcTemp)
ENDPROC &&Get_CompareFiles

